{if ((typeOf _x == 'b_survivor_F') && (!isPlayer _x)) then {deleteVehicle _x}} forEach allUnits;
[MedicalData,3] call BIS_fnc_dataTerminalAnimate;
sleep 5;
_group1=createGroup west;
'b_survivor_F' createUnit [getmarkerPos 'PatientSpawn', _group1,'pat1=this; dostop pat1'];
[pat1] call ace_medical_fnc_handleDamage_advancedSetDamage;
sleep 0.2;
pat1 setUnconscious true;
[pat1, selectRandom[0.7,0.9], "leg_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[pat1, selectRandom[0.7,0.9], "leg_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[pat1, selectRandom[0.7,0.9], "body", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[pat1, selectRandom[0.7,0.9], "head", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[pat1, selectRandom[0.7,0.9], "hand_r", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[pat1, selectRandom[0.7,0.9], "hand_l", selectrandom ["stab","bullet","falling"]] call ace_medical_fnc_addDamageToUnit;
sleep 0.2;
[MedicalData,0] call BIS_fnc_dataTerminalAnimate;
hint 'Zespawnowano pacjenta';